'use client';

import { useState, useRef, useCallback } from 'react';
import { useAnalysisStore } from '@/store';
import { STAR_TIERS, MODELS, DIMENSIONS } from '@/types';
import type { RoadmapItem } from '@/types';
import {
  X,
  Trash2,
  Map,
  Star,
  Download,
  GripVertical,
  Zap,
  Target,
  Rocket,
} from 'lucide-react';

type PhaseTag = 'quick-win' | 'strategic' | 'moonshot';

const PHASE_CONFIG: Record<PhaseTag, { label: string; icon: typeof Zap; color: string }> = {
  'quick-win': { label: 'Quick Wins', icon: Zap, color: '#2DD4BF' },
  strategic: { label: 'Strategic', icon: Target, color: '#F59E0B' },
  moonshot: { label: 'Moonshots', icon: Rocket, color: '#F87171' },
};

function getAutoPhase(starLevel: number): PhaseTag {
  if (starLevel <= 6) return 'quick-win';
  if (starLevel <= 7) return 'strategic';
  return 'moonshot';
}

export function RoadmapPanel() {
  const { roadmapOpen, roadmapItems, removeFromRoadmap, toggleRoadmap, analysis, ideaDetails, reorderRoadmap } =
    useAnalysisStore();
  const [viewMode, setViewMode] = useState<'tier' | 'phase'>('phase');
  const [dragIdx, setDragIdx] = useState<number | null>(null);
  const [dragOverIdx, setDragOverIdx] = useState<number | null>(null);
  const dragItem = useRef<number | null>(null);

  const handleDragStart = useCallback((idx: number) => {
    dragItem.current = idx;
    setDragIdx(idx);
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent, idx: number) => {
    e.preventDefault();
    setDragOverIdx(idx);
  }, []);

  const handleDrop = useCallback((idx: number) => {
    if (dragItem.current !== null && dragItem.current !== idx) {
      reorderRoadmap(dragItem.current, idx);
    }
    dragItem.current = null;
    setDragIdx(null);
    setDragOverIdx(null);
  }, [reorderRoadmap]);

  const handleDragEnd = useCallback(() => {
    dragItem.current = null;
    setDragIdx(null);
    setDragOverIdx(null);
  }, []);

  if (!roadmapOpen) return null;

  // Group by tier
  const groupedByTier = roadmapItems.reduce(
    (acc, item) => {
      const level = item.idea.star_level;
      if (!acc[level]) acc[level] = [];
      acc[level].push(item);
      return acc;
    },
    {} as Record<number, typeof roadmapItems>
  );

  // Group by phase
  const groupedByPhase = roadmapItems.reduce(
    (acc, item) => {
      const phase = getAutoPhase(item.idea.star_level);
      if (!acc[phase]) acc[phase] = [];
      acc[phase].push(item);
      return acc;
    },
    {} as Record<PhaseTag, typeof roadmapItems>
  );

  const handleExportMarkdown = () => {
    let md = `# ${analysis?.company_name ?? 'LangSync'} — Roadmap\n\n`;
    md += `Generated by LangSync 10-Star Experience Platform\n\n`;
    md += `---\n\n`;

    const phases: PhaseTag[] = ['quick-win', 'strategic', 'moonshot'];
    for (const phase of phases) {
      const items = groupedByPhase[phase];
      if (!items || items.length === 0) continue;
      const config = PHASE_CONFIG[phase];
      md += `## Phase: ${config.label}\n\n`;
      for (const item of items) {
        const tier = STAR_TIERS[item.idea.star_level];
        const model = MODELS[item.idea.model_source];
        const dim = DIMENSIONS[item.idea.dimension_key];
        md += `### ${item.idea.title}\n\n`;
        md += `- **Star Level:** ${item.idea.star_level}-Star (${tier.label})\n`;
        md += `- **Model:** ${model.name} — ${model.lens}\n`;
        md += `- **Dimension:** ${dim.label}\n`;
        md += `- **Confidence:** ${item.idea.confidence}\n\n`;
        md += `${item.idea.description}\n\n`;

        const detail = ideaDetails[item.idea_id];
        if (detail) {
          md += `#### Implementation Plan\n\n${detail.what_it_takes}\n\n`;
          md += `#### Quick Start (80/20 Version)\n\n${detail.regression_version}\n\n`;
        }
        md += `---\n\n`;
      }
    }

    md += `\n*Total ideas: ${roadmapItems.length}*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(analysis?.company_name ?? 'langsync').replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-roadmap.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderItem = (item: RoadmapItem, idx: number) => {
    const tier = STAR_TIERS[item.idea.star_level];
    const model = MODELS[item.idea.model_source];
    const isDragging = dragIdx === idx;
    const isDragOver = dragOverIdx === idx;

    return (
      <div
        key={item.id}
        draggable
        onDragStart={() => handleDragStart(idx)}
        onDragOver={(e) => handleDragOver(e, idx)}
        onDrop={() => handleDrop(idx)}
        onDragEnd={handleDragEnd}
        className={`flex items-start gap-2 p-3 rounded-lg bg-ls-dark-card border transition-all group cursor-move ${
          isDragging
            ? 'opacity-50 border-ls-accent/30'
            : isDragOver
            ? 'border-ls-accent/50 bg-ls-accent/5'
            : 'border-ls-dark-border'
        }`}
      >
        <GripVertical className="w-4 h-4 text-gray-600 flex-shrink-0 mt-0.5 opacity-0 group-hover:opacity-100 transition-opacity" />
        <div
          className="w-1 h-full min-h-[2rem] rounded-full flex-shrink-0"
          style={{ backgroundColor: tier.color }}
        />
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-white truncate">
            {item.idea.title}
          </p>
          <div className="flex items-center gap-1.5 mt-1">
            <div
              className="w-1.5 h-1.5 rounded-full"
              style={{ backgroundColor: model.color }}
            />
            <span className="text-xs text-gray-500">
              {model.name}
            </span>
            <span className="text-xs text-gray-600">·</span>
            <span className="text-xs text-gray-500">
              {item.idea.star_level}★
            </span>
          </div>
        </div>
        <button
          onClick={() => removeFromRoadmap(item.idea_id)}
          className="p-1 rounded text-gray-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-all flex-shrink-0"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    );
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 z-30"
        onClick={toggleRoadmap}
      />

      {/* Panel */}
      <div className="fixed right-0 top-0 h-full w-full max-w-md bg-ls-dark border-l border-ls-dark-border z-40 animate-slide-in-right flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-ls-dark-border">
          <div className="flex items-center gap-2">
            <Map className="w-5 h-5 text-ls-accent" />
            <h2 className="text-lg font-bold text-white">Roadmap</h2>
            <span className="text-sm text-gray-500">
              ({roadmapItems.length} items)
            </span>
          </div>
          <div className="flex items-center gap-2">
            {roadmapItems.length > 0 && (
              <button
                onClick={handleExportMarkdown}
                className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-ls-dark-card transition-all"
                title="Export as Markdown"
              >
                <Download className="w-4 h-4" />
              </button>
            )}
            <button
              onClick={toggleRoadmap}
              className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-ls-dark-card transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* View Mode Toggle */}
        {roadmapItems.length > 0 && (
          <div className="flex gap-1 p-3 mx-5 mt-3 bg-ls-dark-card rounded-lg border border-ls-dark-border">
            <button
              onClick={() => setViewMode('phase')}
              className={`flex-1 text-xs py-1.5 rounded transition-all ${
                viewMode === 'phase' ? 'bg-white/10 text-white' : 'text-gray-500 hover:text-gray-300'
              }`}
            >
              By Phase
            </button>
            <button
              onClick={() => setViewMode('tier')}
              className={`flex-1 text-xs py-1.5 rounded transition-all ${
                viewMode === 'tier' ? 'bg-white/10 text-white' : 'text-gray-500 hover:text-gray-300'
              }`}
            >
              By Star Tier
            </button>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5">
          {roadmapItems.length === 0 ? (
            <div className="text-center py-16">
              <Map className="w-12 h-12 text-gray-600 mx-auto mb-4" />
              <p className="text-gray-400 mb-2">No ideas selected yet</p>
              <p className="text-sm text-gray-500">
                Click the + button on any idea card to add it to your roadmap.
              </p>
            </div>
          ) : viewMode === 'phase' ? (
            <div className="space-y-6">
              {(['quick-win', 'strategic', 'moonshot'] as PhaseTag[]).map((phase) => {
                const items = groupedByPhase[phase];
                if (!items || items.length === 0) return null;
                const config = PHASE_CONFIG[phase];
                const Icon = config.icon;
                return (
                  <div key={phase}>
                    <div className="flex items-center gap-2 mb-3">
                      <Icon className="w-4 h-4" style={{ color: config.color }} />
                      <h3 className="text-sm font-semibold" style={{ color: config.color }}>
                        {config.label}
                      </h3>
                      <span className="text-xs text-gray-600">({items.length})</span>
                    </div>
                    <div className="space-y-2">
                      {items.map((item) => renderItem(item, roadmapItems.indexOf(item)))}
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="space-y-6">
              {([6, 7, 8, 9] as const).map((level) => {
                const items = groupedByTier[level];
                if (!items || items.length === 0) return null;
                const tier = STAR_TIERS[level];
                return (
                  <div key={level}>
                    <div className="flex items-center gap-2 mb-3">
                      <Star
                        className="w-4 h-4"
                        style={{ color: tier.color }}
                        fill={tier.color}
                      />
                      <h3
                        className="text-sm font-semibold"
                        style={{ color: tier.color }}
                      >
                        {level}-Star · {tier.label}
                      </h3>
                    </div>
                    <div className="space-y-2">
                      {items.map((item) => renderItem(item, roadmapItems.indexOf(item)))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer Summary */}
        {roadmapItems.length > 0 && (
          <div className="p-5 border-t border-ls-dark-border space-y-3">
            {/* Phase summary */}
            <div className="flex gap-3 justify-center">
              {(['quick-win', 'strategic', 'moonshot'] as PhaseTag[]).map((phase) => {
                const count = groupedByPhase[phase]?.length ?? 0;
                if (count === 0) return null;
                const config = PHASE_CONFIG[phase];
                return (
                  <div key={phase} className="flex items-center gap-1.5">
                    <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: config.color }} />
                    <span className="text-xs text-gray-500">
                      {count} {config.label.toLowerCase()}
                    </span>
                  </div>
                );
              })}
            </div>
            <button
              onClick={handleExportMarkdown}
              className="w-full py-2.5 rounded-lg bg-gradient-to-r from-ls-accent to-ls-teal text-ls-dark text-sm font-semibold hover:shadow-lg hover:shadow-ls-accent/20 transition-all"
            >
              Export Roadmap as Markdown
            </button>
          </div>
        )}
      </div>
    </>
  );
}
